//-----------------------------------------------------------------------------
//  Basler Data Processing SDK
//  Copyright (c) 2021-2023 Basler AG
//  http://www.baslerweb.com
//  Author:  BR
//-----------------------------------------------------------------------------
//
// This file is autogenerated. Changes will be overwritten.
// File contains pylon data processing version defines.

#pragma once

#define PYLON_DATAPROCESSING_VERSION_MAJOR           1
#define PYLON_DATAPROCESSING_VERSION_MINOR           2
#define PYLON_DATAPROCESSING_VERSION_SUBMINOR        0
#define PYLON_DATAPROCESSING_VERSION_BUILD           5436

#define PYLON_DATAPROCESSING_VERSIONSTRING_MAJOR     "1"
#define PYLON_DATAPROCESSING_VERSIONSTRING_MINOR     "2"
#define PYLON_DATAPROCESSING_VERSIONSTRING_SUBMINOR  "0"
#define PYLON_DATAPROCESSING_VERSIONSTRING_BUILD     "5436"
#define PYLON_DATAPROCESSING_VERSIONSTRING_EXTENSION "5436"

#define PYLON_DATAPROCESSING_GIT_REVISION            "ce1efa3441b89f2fb0e38d041046084cd825b837"
#define PYLON_DATAPROCESSING_VERSION_SUFFIX          "_v1_2"
